-- MySQL Script generated by MySQL Workbench
-- Sun Dec 23 16:18:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema school_from_future
-- -----------------------------------------------------
-- PISS

-- -----------------------------------------------------
-- Schema school_from_future
--
-- PISS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_from_future` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;

USE `school_from_future` ;

-- -----------------------------------------------------
-- Table `school_from_future`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`Right`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Right` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `right_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`role_right`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`role_right` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  `right_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_name_idx` (`role_name` ASC) VISIBLE,
  CONSTRAINT `role_name`
    FOREIGN KEY (`role_name`)
    REFERENCES `school_from_future`.`Role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `right_name`
    FOREIGN KEY (`right_name`)
    REFERENCES `school_from_future`.`Right` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `school_from_future`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`User` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `pass` VARCHAR(50) NOT NULL,
  `role` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Usercol_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `role_idx` (`role` ASC) VISIBLE,
  CONSTRAINT `role`
    FOREIGN KEY (`role`)
    REFERENCES `school_from_future`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`School`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`School` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Student` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT NOT NULL,
  `class` INT NOT NULL,
  `class_number` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_from_future`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school_from_future`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Teacher` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `school_id_idx` (`school_id` ASC) VISIBLE,
  CONSTRAINT `teacher_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_from_future`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teacher_school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `school_from_future`.`School` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Admin` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `admin_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `school_from_future`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`School_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`School_subject` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(60) NULL,
  `teacher_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_from_future`.`Teacher` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`Student_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Student_subject` (
  `student_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_id`, `subject_id`),
  INDEX `subject_id_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_from_future`.`Student` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_from_future`.`School_subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`student_note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`student_note` (
  `student_id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(45) NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_id`, `subject_id`),
  CONSTRAINT `note_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_from_future`.`Student_subject` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `note_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_from_future`.`Student_subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`student_absence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`student_absence` (
  `student_id` INT UNSIGNED NOT NULL,
  `count` DECIMAL(3,2) NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`student_id`, `subject_id`),
  CONSTRAINT `absence_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_from_future`.`Student_subject` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `absence_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_from_future`.`Student_subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`student_grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`student_grade` (
  `student_id` INT UNSIGNED NOT NULL,
  `subject_id` INT UNSIGNED NOT NULL,
  `grade` INT UNSIGNED NULL,
  PRIMARY KEY (`student_id`, `subject_id`),
    CONSTRAINT `grade_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `school_from_future`.`Student_subject` (`student_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grade_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_from_future`.`Student_subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_from_future`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school_from_future`.`Event` (
  `subject_id` INT UNSIGNED NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`subject_id`),
  CONSTRAINT `event_subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_from_future`.`School_subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
